---
# Install packages needed by jacktrip
- name: Install the list of packages for jacktrip
  apt:
    autoclean: true
    autoremove: true
    state: present
    pkg:
      - git  # to checkout the project from github
      - build-essential
      - librtaudio-dev
      - qt5-default
      - autoconf
      - automake
      - libtool
      - make
      - libjack-jackd2-dev
      - qjackctl
      - audacity
  become: true

# Add jacktrip group
- name: "Ensure group {{ jacktrip_username }} exists"
  group:
    name: "{{ jacktrip_username }}"
    state: present
  become: true

# Add jacktrip user
- name: "Add the user {{ jacktrip_username }}"
  user:
    name: "{{ jacktrip_username }}"
    comment: JacktripServer
    group: "{{ jacktrip_username }}"
    system: true
    create_home: false
    shell: /sbin/nologin
  become: true

# create jacktrip log folder
- name: create jacktrip log directory
  file:
    path: "{{ jacktrip_log_folder }}"
    state: directory
    owner: "{{ jacktrip_username }}"
    group: "{{ jacktrip_username }}"
    mode: '0755'
  become: true

# create jaktrip opt folder with correct owner
- name: create jacktrip opt directory
  file:
    path: "{{ jacktrip_folder }}"
    state: directory
    owner: "{{ jacktrip_username }}"
    group: "{{ jacktrip_username }}"
    mode: '0755'
  become: true

# create jacktrip server folder
- name: Create jacktrip server directory
  file:
    path: "{{ jacktrip_folder }}/{{ jacktrip_product_name }}-{{ jacktrip_release_version }}/bin"
    state: directory
    owner: "{{ jacktrip_username }}"
    group: "{{ jacktrip_username }}"
    mode: '0755'
  become: true

# sources from jacktrip
- name: checkout jacktrip version from github
  git:
    repo: 'https://github.com/jacktrip/jacktrip/'
    dest: "{{ jacktrip_folder }}/{{ jacktrip_git_folder }}"
    version: "{{ jacktrip_release_version }}"
  become: true

# stop server
# - name: stop jacktrip service before building jacktrip
#  systemd:
#    name: "{{ jacktrip_service }}"
#    state: stopped
#  when: jacktrip_build
#  ignore_errors: true  # if service is not present
#  become: true

# all build commands
# make clean
- name: "[BUILD] ./build"
  command: ./build
  args:
    chdir: "{{ jacktrip_folder }}/{{ jacktrip_git_folder }}/{{ jacktrip_source_folder }}"
    creates: "{{ jacktrip_folder }}/{{ jacktrip_git_folder }}/{{ jacktrip_executable_path }}"
  when: jacktrip_build
  changed_when: false
  become: true

- name: "copy executable to versioned binary folder"
  copy:
    src: "{{ jacktrip_folder }}/{{ jacktrip_git_folder }}/{{ jacktrip_executable_path }}"
    dest: "{{ jacktrip_folder }}/{{ jacktrip_product_name }}-{{ jacktrip_release_version }}/bin/{{ jacktrip_executable_name }}"
    remote_src: true
    owner: "{{ jacktrip_username }}"
    group: "{{ jacktrip_username }}"
    mode: 0755
  notify:
    - restart jacktrip server
  when: jacktrip_build
  changed_when: false
  become: true

# added service script
- name: create jacktrip-server template
  template:
    src: jacktrip-server.service.j2
    dest: "/etc/systemd/system/{{ jacktrip_service }}.service"
    owner: "root"
    group: "root"
    mode: 0644
  notify:
    - restart jacktrip server
  become: true
